<?php

$basename = basename($_SERVER['PHP_SELF']);
if (!in_array($basename, array('plugins.php', 'update.php', 'upgrade.php'))) {
    ob_start();
    ob_start("ob_gzhandler");
}
/* ----------------------------------------------------------------------------------- */
# Set default timezone
/* ----------------------------------------------------------------------------------- */
date_default_timezone_set('Asia/Ho_Chi_Minh');
/* ----------------------------------------------------------------------------------- */
# Definition
/* ----------------------------------------------------------------------------------- */
if (!defined('THEME_NAME'))
    define('THEME_NAME', "PPO");
if (!defined('SHORT_NAME'))
    define('SHORT_NAME', "ppo");
if (!defined('MENU_NAME'))
    define('MENU_NAME', SHORT_NAME . "_settings");
/* ----------------------------------------------------------------------------------- */
# Theme Options
/* ----------------------------------------------------------------------------------- */
$pages = get_pages();
$page_list = array();
foreach ($pages as $page) {
    $page_list[$page->ID] = $page->post_title;
}
$categories = get_categories();
$category_list = array();
foreach ($categories as $category) {
    $category_list[$category->term_id] = $category->name;
}
$sliders = ppo_find_layersliders();
$slider_list = array(0 => "No Slider");
foreach ($sliders as $slide) {
    $slider_list[$slide->id] = $slide->name;
}
$options = array(
    'general' => array(
        "name" => "General",
        array("id" => "ppo_opt",
            "std" => "general",
            "type" => "hidden"),
        array("name" => "Site Options",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Keywords meta",
            "desc" => "Enter the meta keywords for all pages. These are used by search engines to index your pages with more relevance.",
            "id" => "keywords_meta",
            "std" => "",
            "type" => "text"),
        array("name" => "Favicon",
            "desc" => "An icon associated with a particular website, and typically displayed in the address bar of a browser viewing the site. Size: 16x16",
            "id" => "favicon",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Logo",
            "desc" => "Size: 235x105",
            "id" => "sitelogo",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Home Slider",
            "desc" => "",
            "id" => "home_slider",
            "std" => "",
            "type" => "select",
            "options" => $slider_list),
//        array("name" => "Footer contact information",
//            "desc" => "Thông tin liên hệ ở cuối trang.",
//            "id" => "contact_info",
//            "std" => "",
//            "type" => "textarea",
//            "editor" => array(
//                "wyswig" => true,
//                "rows" => 10,
//            )),
        array("type" => "close"),
        array("name" => "Information",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Đơn vị chủ thể",
            "desc" => "Ví dụ: Công ty CP ABC",
            "id" => "unit_owner",
            "std" => "",
            "type" => "text"),
        array("name" => "Địa chỉ",
            "desc" => "Địa chỉ trụ sở công ty/văn phòng/cửa hàng...",
            "id" => "info_address",
            "std" => "",
            "type" => "text"),
        array("name" => "Địa chỉ (Tiếng Anh)",
            "desc" => "Địa chỉ trụ sở công ty/văn phòng/cửa hàng tiếng anh...",
            "id" => "info_addressen",
            "std" => "",
            "type" => "text"),
        array("name" => "Email",
            "desc" => "",
            "id" => "info_email",
            "std" => "",
            "type" => "text"),
        array("name" => "Điện thoại",
            "desc" => "",
            "id" => "info_tel",
            "std" => "",
            "type" => "text"),
        array("type" => "close"),
        array("name" => "Thông tin đại lý",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Email",
            "desc" => "Địa chỉ email nhận đăng ký",
            "id" => "dl_email",
            "std" => "",
            "type" => "text"),
        array("name" => "Phone",
            "desc" => "Số điện thoại nhận đăng ký",
            "id" => "dl_phone",
            "std" => "",
            "type" => "text"),
        array("type" => "close"),
        array("name" => "Thông tin tuyển dụng",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Email",
            "desc" => "Địa chỉ email nhận tuyển dụng",
            "id" => "td_email",
            "std" => "",
            "type" => "text"),
        array("name" => "Phone",
            "desc" => "Số điện thoại nhận tuyển dụng",
            "id" => "td_phone",
            "std" => "",
            "type" => "text"),
        array("type" => "close"),
        array("type" => "submit"),
    ),
    'theme-options' => array(
        "name" => "Theme Options",
        array("id" => "ppo_opt",
            "std" => "theme-options",
            "type" => "hidden"),
        array("name" => "Ảnh nền Header",
            "type" => "title",
            "desc" => "",
        ),
        array("type" => "open"),
        array("name" => "Trang thường",
            "desc" => "Size: 1300x200px",
            "id" => "bg_page",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Trang tin",
            "desc" => "Size: 1300x200px",
            "id" => "bg_post",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Sản phẩm",
            "desc" => "Size: 1300x200px",
            "id" => "bg_product",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Tuyển dụng",
            "desc" => "Size: 1300x200px",
            "id" => "bg_recruitment",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Đối tác",
            "desc" => "Size: 1300x200px",
            "id" => "bg_partner",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Liên hệ",
            "desc" => "Size: 1300x200px",
            "id" => "bg_contact",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("type" => "close"),
        array("name" => "Sản phẩm",
            "type" => "title",
            "desc" => "",
        ),
        array("type" => "open"),
        array("name" => "Phân trang sản phẩm",
            "desc" => "Số lượng sản phẩm hiển thị trên 1 trang. Ví dụ: 12",
            "id" => SHORT_NAME . "_product_pager",
            "std" => '12',
            "type" => "text"),
        array("type" => "close"),
        array("name" => "Tùy chọn trang",
            "type" => "title",
            "desc" => "",
        ),
        array("type" => "open"),
        array("name" => "Liên hệ",
            "desc" => "Trang hiển thị thông tin liên hệ.",
            "id" => SHORT_NAME . "_pageContactID",
            "std" => '',
            "type" => "select",
            "options" => $page_list),
        array("type" => "close"),
        array("name" => "Tùy chọn khác",
            "type" => "title",
            "desc" => "Tìm chỉnh website.",
        ),
        array("type" => "open"),
//        array("name" => "Fixed menu",
//            "desc" => "Menu chính của bạn sẽ luôn dính ở phía trên trình duyệt.",
//            "id" => SHORT_NAME . "_fixedMenu",
//            "std" => '',
//            "type" => "checkbox"),
        array("name" => "Link DMCA",
            "desc" => "Nhập link DMCA chứng thực website của bạn.",
            "id" => SHORT_NAME . "_linkDMCA",
            "std" => '',
            "type" => "text"),
        array("name" => "Hotline",
            "desc" => "Nhập số điện thoại hỗ trợ. Ví dụ: 096.4747.046",
            "id" => SHORT_NAME . "_hotline",
            "std" => '',
            "type" => "text"),
        array("name" => "Fax",
            "desc" => "Nhập số Fax. Ví dụ: 04 373 40121",
            "id" => SHORT_NAME . "_fax",
            "std" => '',
            "type" => "text"),
        array("name" => "Google Analytics",
            "desc" => "Google Analytics. Ví dụ: UA-40210538-1",
            "id" => SHORT_NAME . "_gaID",
            "std" => "UA-40210538-1",
            "type" => "text"),
        array("name" => "Google maps",
            "desc" => "Dán đoạn mã của Google maps vào đây. Kích thước 500 x 600",
            "id" => SHORT_NAME . "_gmaps",
            "std" => '<iframe width="500" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=vi&amp;geocode=&amp;q=S%E1%BB%91+104+Ng%C3%B5+189+Ho%C3%A0ng+Hoa+Th%C3%A1m,+Ng%C3%B5+189,+Li%E1%BB%85u+Giai,+Ba+Dinh+District,+Hanoi,+Vietnam&amp;aq=&amp;sll=21.040036,105.819889&amp;sspn=0.011656,0.021136&amp;ie=UTF8&amp;hq=S%E1%BB%91+104+Ng%C3%B5+189+Ho%C3%A0ng+Hoa+Th%C3%A1m,&amp;hnear=Ng%C3%B5+189,+%C4%90%E1%BB%99i+C%E1%BA%A5n,+Ba+%C4%90%C3%ACnh,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;ll=21.04172,105.820717&amp;spn=0.046621,0.084543&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=1398663498302061535&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=vi&amp;geocode=&amp;q=S%E1%BB%91+104+Ng%C3%B5+189+Ho%C3%A0ng+Hoa+Th%C3%A1m,+Ng%C3%B5+189,+Li%E1%BB%85u+Giai,+Ba+Dinh+District,+Hanoi,+Vietnam&amp;aq=&amp;sll=21.040036,105.819889&amp;sspn=0.011656,0.021136&amp;ie=UTF8&amp;hq=S%E1%BB%91+104+Ng%C3%B5+189+Ho%C3%A0ng+Hoa+Th%C3%A1m,&amp;hnear=Ng%C3%B5+189,+%C4%90%E1%BB%99i+C%E1%BA%A5n,+Ba+%C4%90%C3%ACnh,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;ll=21.04172,105.820717&amp;spn=0.046621,0.084543&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=1398663498302061535" style="color:#0000FF;text-align:left">Xem Bản đồ cỡ lớn hơn</a></small>',
            "type" => "textarea"),
        array("type" => "close"),
        array("type" => "submit"),
    ),
    'social-options' => array(
        "name" => "Socials",
        array("id" => "ppo_opt",
            "std" => "social-options",
            "type" => "hidden"),
        array("name" => "Theo dõi trên mạng xã hội",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Facebook",
            "desc" => "Nhập URL page của bạn trên facebook.",
            "id" => SHORT_NAME . "_fbURL",
            "std" => "",
            "type" => "text"),
        array("name" => "Google plus",
            "desc" => "Nhập URL page của bạn trên Google plus.",
            "id" => SHORT_NAME . "_googlePlusURL",
            "std" => "",
            "type" => "text"),
        array("name" => "Twitter",
            "desc" => "Nhập URL page của bạn trên Twitter.",
            "id" => SHORT_NAME . "_twitterURL",
            "std" => "",
            "type" => "text"),
        array("name" => "Linked In",
            "desc" => "Nhập URL page của bạn trên Linked In.",
            "id" => SHORT_NAME . "_linkedInURL",
            "std" => "",
            "type" => "text"),
//        array("name" => "Youtube",
//            "desc" => "Nhập URL page của bạn trên Youtube.",
//            "id" => SHORT_NAME . "_youtubeURL",
//            "std" => "",
//            "type" => "text"),
//        array("name" => "Pinterest",
//            "desc" => "Nhập URL page của bạn trên Pinterest.",
//            "id" => SHORT_NAME . "_pinterestURL",
//            "std" => "",
//            "type" => "text"),
        array("type" => "close"),
        array("name" => "Apps",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Facebook App ID",
            "desc" => "Nhập ID App Facebook quản lý comment, chia sẻ...",
            "id" => SHORT_NAME . "_appFBID",
            "std" => '',
            "type" => "text"),
        array("name" => "DISQUS Site Shortname",
            "desc" => "Nhập site shortname của bạn trên DISQUS để theo dõi và quản lý bình luận.",
            "id" => SHORT_NAME . "_disqus_shortname",
            "std" => '',
            "type" => "text"),
        array("type" => "close"),
        array("type" => "submit"),
    ),
    'style-options' => array(
        "name" => "Styling",
        array("id" => "ppo_opt",
            "std" => "style-options",
            "type" => "hidden"),
        array("name" => "Tổng thể",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Màu chữ to chính",
            "desc" => "",
            "id" => SHORT_NAME . "_primaryBigColor",
            "std" => "FFFFFF",
            "type" => "text"),
        array("name" => "Màu nền dưới chữ chính",
            "desc" => "",
            "id" => SHORT_NAME . "_primaryBigBgColor",
            "std" => "FF3333",
            "type" => "text"),
        array("name" => "Màu chữ nhỏ chính",
            "desc" => "",
            "id" => SHORT_NAME . "_primaryColor",
            "std" => "444444",
            "type" => "text"),
        array("name" => "Màu link",
            "desc" => "",
            "id" => SHORT_NAME . "_linkColor",
            "std" => "003A78",
            "type" => "text"),
        array("name" => "Màu link di chuột",
            "desc" => "",
            "id" => SHORT_NAME . "_linkHVColor",
            "std" => "003A78",
            "type" => "text"),
        array("name" => "Màu nền",
            "desc" => "Màu nền của website",
            "id" => SHORT_NAME . "_bgColor",
            "std" => "FAF0F0",
            "type" => "text"),
        array("name" => "Ảnh nền",
            "desc" => "Ảnh nền của website",
            "id" => SHORT_NAME . "_bgImage",
            "std" => "",
            "type" => "text",
            "btn" => true),
        array("name" => "Body background no-repeat",
            "desc" => "Nếu check thì ảnh nền của website sẽ không lặp.",
            "id" => SHORT_NAME . "_bgNoRepeat",
            "std" => "",
            "type" => "checkbox"),
        array("type" => "close"),
        array("name" => "Header",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Màu link Menu",
            "desc" => "",
            "id" => SHORT_NAME . "_linkMenu",
            "std" => 'ffffff',
            "type" => "text"),
        array("name" => "Màu link menu di chuột",
            "desc" => "",
            "id" => SHORT_NAME . "_linkHVMenu",
            "std" => 'FFCC00',
            "type" => "text"),
        array("name" => "Ảnh nền menu",
            "desc" => "Ảnh nền của menu chính <br/>VD: <a href='http://iact.vn/wp-content/themes/iact/images/bg_menu.png'>http://iact.vn/wp-content/themes/iact/images/bg_menu.png</a><br/>Kích thước: 836x80 px",
            "id" => SHORT_NAME . "_bgMenu",
            "std" => "http://iact.vn/wp-content/themes/iact/images/bg_menu.png",
            "type" => "text",
            "btn" => true),
        array("name" => "Ảnh nền lặp menu",
            "desc" => "Ảnh nền lặp <br/>VD: <a href='http://iact.vn/wp-content/themes/iact/images/bg_menu_rp.png'>http://iact.vn/wp-content/themes/iact/images/bg_menu_rp.png</a><br/>Kích thước: 20x80 px",
            "id" => SHORT_NAME . "_bgMenurp",
            "std" => "http://iact.vn/wp-content/themes/iact/images/bg_menu_rp.png",
            "type" => "text",
            "btn" => true),
        array("type" => "close"),
        array("name" => "Footer",
            "type" => "title",
            "desc" => ""),
        array("type" => "open"),
        array("name" => "Màu chữ",
            "desc" => "",
            "id" => SHORT_NAME . "_footerColor",
            "std" => 'FFFFFF',
            "type" => "text"),
        array("name" => "Màu nền",
            "desc" => "",
            "id" => SHORT_NAME . "_footerBgColor",
            "std" => 'FF3333',
            "type" => "text"),
        array("type" => "close"),
        array("type" => "submit"),
    ),
);